version: '3' #This denotes that we are using version 3 of Docker Compose
services:
  #This section defines all the different containers we will create.

  nide-portfolio-server:
    #This is the name of our application.

    ports:
      #This is used to map the container’s ports to the host machine.
      - "5000:5000"
    build:
      #This specifies the location of our Dockerfile
      context: /
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.server

    # env_file:
    #   - .env
